# Generated by Django 5.0 on 2023-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path_id',
            field=models.IntegerField(),
        ),
    ]
