# Generated by Django 5.0 on 2023-12-26 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
