# Generated by Django 5.0 on 2023-12-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image_path_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_path_id',
        ),
    ]
