# Generated by Django 5.0 on 2023-12-25 14:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', upload_to=users.models.profile_image_dir),
        ),
    ]
