# Generated by Django 5.0 on 2023-12-25 14:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, default='profile_backgrounds/default_background.png', upload_to=users.models.profile_background_dir),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', upload_to=users.models.profile_image_dir),
        ),
    ]
