# Generated by Django 5.0 on 2023-12-25 14:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, default='profile_backgrounds/default_background.jpg', upload_to=users.models.profile_background_dir),
        ),
    ]
