# Generated by Django 5.0 on 2023-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Connectify - Where Connections Unite!', max_length=100),
        ),
    ]
